services:
  flask-api:
    image: python:3.13
    container_name: flask_api
    build:
      context: ./flask-api
    env_file:
      - ./flask-api/.env
    depends_on:
      - redis
    ports:
      - "3101:3101"
    volumes:
      - ./flask-api/:/opt/app

  redis: 
    image: redis:7.2
    container_name: redis_server
    ports:
      - "6379:6379"
  
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
  
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"

volumes:
  mongo_data:
    name: mongo_data
    driver: local
